update

diff --git a/sb-script/sb_disconnect b/sb-script/sb_disconnect
--- a/sb-script/sb_disconnect
+++ b/sb-script/sb_disconnect
@@ -29,3 +29,6 @@ EOF
 )"
 
 mosquitto_pub -h ${MQTTIP} -t ${TOPIC} -d -m "${PAYLOAD}"
+if [ $? != 0 ]; then
+    echo "error"
+fi
